### ISSUE TITLE
Javascript para situar los submenús

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#10]
Los submenús ya no se abren en su sitio, se abren pegados al borde izquierdo del viewport. Me imagino que pasa esto desde que hemos reorganizado los JS en el pie y en el header, aunque me eacabo de percatar.

**Comment by aitormendez** [comment]
Por el mismo motivo, han dejado de funcionar los checkboxes que hay en el lateral de esta página: http://iac.e451.net/biblioteca-de-documentos.html#

**Comment by aitormendez** [comment]
Lo que estaba pasando es que:
1. No había corrido la tarea concat de grunt
2. Había que eliminar la etiqueta `<script>`de uno dellos scripts fuente en /js-personal

Después de hacer esto ya funcionan los checkboxes pero aún no funcionan los menús :cry:

**Comment by muihlinn** [comment]
commit 61720fa0ab409a2ed1ad8023e288a0a4673f9074
