### ISSUE TITLE
Quienes somos, etiqueta activo inconsistente con las nuevas cabeceras.

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#100]
el "enlace" activo no se muestra como debería.
Las cabeceras de esta página, en tu proyecto no son consistentes con las nuevas 
```html
<div class="col-izquierda-b">
  <header>
    <aside>
      <h3>iac</h3>
      <h4>Quiénes somos</h4>
    </aside>
   </header>
  (listado de opciones... (junta, socios protectores / benefactores , socios)
</div>
```
He estado mirando cómo podría solucionarlo, pero no me aclaro.

http://iac.imaginarymagnitude.net/quienes-somos/junta.html

**Comment by aitormendez** [comment]
Tienes que hacer lo que pone en el comentario 5 de este issue:
https://github.com/aitormendez/iac-web/issues/98

**Comment by muihlinn** [comment]
Gracias, no era capaz de verlo con tanta cosa en la cabeza.
