### ISSUE TITLE
Indicación de carga de datos en infinite scroll

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#103]
Indicación de carga de datos en infinite scroll

**Comment by aitormendez** [comment]
49fa84d20ba5cc84b44eac4a8f1ca1a56a177528

**Comment by muihlinn** [comment]
¿Les puedo poner identificadores y/o clases a los divs nuevos para poder manipularlos desde js sin problema? Necesitaría controlar la visibilidad según convenga.

**Comment by aitormendez** [comment]
Sí, lo que añadas no afectará, sólo lo que elimines.

**Comment by muihlinn** [comment]
perfecto.
