### ISSUE TITLE
Plantilla visualización de textos extendidos del perfil de usuario

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#106]
Debería ser ligeramente distinta de la plantilla base de documento. Es decir, no debe confundirse con contenido editorial del IAC.

**Comment by aitormendez** [comment]
No sé si lo entiendo bien. ¿Quieres decir que los documentos que haya subido un usuario no deberían ser iguales que los doumentos del IAC?

**Comment by muihlinn** [comment]
Exactamente, pienso que el contenido de un usuario no debería confundirse con las cosas que publique el IAC. No es que necesite ser cambio radical, sólo alguna forma de diferenciarlo, Creo que Marina contestó a esto en algún email.

**Comment by aitormendez** [comment]
A falta de una respuesta del cliente, hacemos lo que proponía en el email:
http://iac-web/doc-usuario.html

**Comment by muihlinn** [comment]
me parece bien, sólo se necesita un botón o enlace de "leer más"

**Comment by aitormendez** [comment]
Está hecho, te lo he puesto en su issue correspondiente 
https://github.com/aitormendez/iac-web/issues/111
