### ISSUE TITLE
Remodelación menús

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#108]
1. Eliminar secciones de la columna lateral izquierda en Observatorio y Noticias. Sólo permanece la sección en la que uno se encuentra.
2. Meter el título de los documentos del menú IAC (Qué es el IAC, Estatutos, Quiénes somos, Cómo unirse al IAC y Ventajas para socios) como títulos de sección, utilizando el mismo marcado.

**Comment by aitormendez** [comment]
Luis, creo que esto lo puedes hacer con el marcado que tienes. Si no, dímelo.

**Comment by muihlinn** [comment]
Entiendo que sí; te diré si tengo alguna o problema.

**Comment by muihlinn** [comment]
Tengo una pregunta para confirmar el marcaje:

¿las categorías de enlaces de "investigación:enlaces" y "consejo territorial" quedan en marcaje tal y como están [`nav.menu-lateral ul li a`] o pasan a ser [`aside h4.ariadna-h4`] ?

Entiendo que los títulos de los documentos del menu IAC "que es IAC" pasan a ser  [`aside h4.ariadna-h4`] y que si añaden categorías a secciones que ahora no tienen (documentos, prensa, las del area de socios... se comportan como lo haría el consejo territorial o investigación:enlaces)

**Comment by aitormendez** [comment]
Yo lo dejaría como está ¿Puedes probar a ver si funciona?

**Comment by muihlinn** [comment]
Creo que habrá que tocar algo los estilos de los márgenes para alinear bien la parte superior del contenido con la columna izquierda. A ver si puedo subirlo luego para que lo veas

**Comment by muihlinn** [comment]
Subido, te copio aquí las observaciones que he enviado en el hilo de email para considerar posibles cambios en el css.

- No estoy seguro si el publicado debe ir ahí (donde iba), en otro sitio, o no aparecer:
	http://iac.imaginarymagnitude.net/que-es.html

- Visible en la mísma página, y en otras, la banda turquesa ahora no tiene tanto contenido como solía tener en prácticamente todas las secciones y descabalga la columna de la derecha en ocasiones.
	
- En estas páginas de documento individual ¿el titular se mantiene ahí o debería pasar a la columna central?
	http://iac.imaginarymagnitude.net/observatorio/opinion/la-educacion-arte-normalizar-situacion.html

- Al eliminar el titular de algunas secciones y sustituirla por una "etiqueta" algunos márgenes parecen fuera de sitio en relación con el ariadna y el margen superior de la columna central (esto puede ser simplemente impresión mía) .  Por ejemplo:

	http://iac.imaginarymagnitude.net/unirse-iac.html

**Comment by aitormendez** [comment]
1. El publicado no debería aparecer en una sección fija, en mi opinión.
2. Corrijo la banda de color en el CSS.
3. Yo dejaría ahí el titular si nadie dice lo contrario.
4. ¿A qué márgenes te refieres?

**Comment by muihlinn** [comment]
Marina contestó a (la mayoría de esto) en un email. 
Los márgenes son los superiores de la columna central y la alineación del texto con respecto a la columna izquierda.

**Comment by aitormendez** [comment]
Perdona, pero sigo sin entenderlo

**Comment by muihlinn** [comment]
Entonces será cosa mía. ignóralo, si no se queja nadie...
