### ISSUE TITLE
Perfil: boton email/editar

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#109]
al poner la ocupación ha pasado de estar junto al nombre a bajo la ocupación.
Quizás sea tan simple como cambiar el orden de las líneas.
 
![screen shot 2016-04-07 at 18 11 00](https://cloud.githubusercontent.com/assets/7160350/14358188/2d87db76-fcec-11e5-8a86-db418196ed26.png)

**Comment by aitormendez** [comment]
No se entiende la frase. Por favor, revisa la redacción.

**Comment by muihlinn** [comment]
.

**Comment by aitormendez** [comment]
Hecho 31ad0bcb8e415da1c4f6fba2404ea9cfc0751dd5
