### ISSUE TITLE
Pestaña de redes sociales. No hay iconos de enlace.

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#11]
`    <div class="social-cont facebook col-sm-6">`
`      <a href="https://www.facebook.com/iac.instituto.de.arte.contemporaneo" class="icon-facebook-24 icon-social" target="blank"></a>`
`      <p class="etiq">{{ trans('iac.facebook') }}</p>`
`    </div>`

Twitter igual

**Comment by aitormendez** [comment]
Yo sí los veo

**Comment by muihlinn** [comment]
Problema local con mi usuario.
