### ISSUE TITLE
Perfil: decidir qué botón se usa para editar el perfil

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#110]
Si el lápiz (como el resto) o el botón inferior de "editar opciones de usuario"

**Comment by aitormendez** [comment]
Pues no lo sé dado que lo de las opciones de usuario no lo he visto nunca ni sé cómo es. Si me puedes mandar un enlace de cómo queda te lo agradecería.

**Comment by muihlinn** [comment]
está en tu email desde antes de poner los issues; no voy a poner aquí las claves

**Comment by aitormendez** [comment]
¿Puedes mandarme las clave otra vez, por favor?

**Comment by muihlinn** [comment]
enviado.

**Comment by aitormendez** [comment]
Lo que yo veo es que son dos cosas distintas, una las opciones de usuario y otra la edición del statement. Yo creo que cada uno debe tener su botón. El del lapiz para el statement y el de opciones de usuario para las opciones de usuario, a no ser que tengas alguna objeción.

**Comment by muihlinn** [comment]
Np

**Comment by muihlinn** [comment]
Mírate la página, Esto ya lo hablamos varias veces.  La edición del statement está junto al statement, como el resto de secciones.

Las opciones de usuario y el email aparecían junto al nombre. Luego se pensó que quizás se quitase el botón de edición de junto al nombre y se pusiese el grande con todo el texto. De lo que se trata ahora es de decidir cuál de los dos se queda.

**Comment by aitormendez** [comment]
Ok. Ya lo he entendido. Creo que si hicimos el cambio sería para consolidarlo ¿no? O sea, si ya estaba hecho ¿por qué volver a repensar esta cuestión? No recuerdo exactamente las razones de este cambio pero si no te parece mal yo diría que el botón grande de abajo.

**Comment by muihlinn** [comment]
Ya está hecho.
Supongo que la razón de repasarlo es porque en algún momento no se tuvo claro y seguian apareciendo ambos y el botón de contacto que tiene que seguir apareciendo si no eres el titular del perfil, con lo que algo de sentido tienen ambos. En cualquier caso está como has dicho.
