### ISSUE TITLE
Perfil: El highligth del botón de edición de los enlaces añadidos se confunde con el fondo

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#112]
Cuando tienes la opción de editar el perfil el color de resalte del botón de edición es – lógicamente – el mismo que el color de resalte del row del enlace, lo que hace que el botón se vuelva invisible salvo por el icono.

**Comment by aitormendez** [comment]
No pasa nada, si nadie se ha quejado se queda así porque no queda mal y es totalmente funcional.
