### ISSUE TITLE
Perfil: Menu edición

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#113]
Confirmar que esa es la posición correcta del menú de edición

**Comment by aitormendez** [comment]
¿qué menú es ese? no lo entiendo

**Comment by muihlinn** [comment]
el que tienes en el diseño (dentro del perfil) con botones para crear las entradas del usuario (imagen, texto, enlace) en amarillo.

**Comment by aitormendez** [comment]
Confirmado. Me parece correcto.
