### ISSUE TITLE
Perfil: margen inferior entre el boton de "editar opciones de usuario" y siguiente elemento si el usuario no tiene especificada una página web.

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#114]
**Considerar sólo si el #110 favorece a mantener este botón**

El botón se pega al siguiente elemento.

Ojo, la página web es la que se define en las opciones de usuario, no los enlaces, si la tiene, mantiene un margen correcto.

**Comment by aitormendez** [comment]
arreglado en el css

**Comment by muihlinn** [comment]
Reopened: Sigue ocurriendo, al menos con el menú de introducción de datos.

**Comment by aitormendez** [comment]
Parece como que no has actualizado el CSS. El tuyo es distinto del mío.

**Comment by muihlinn** [comment]
Actualicé todo el proyecto cuando me asignaste el issue, por lo que debería estar. En cualquier caso, vuelto a hacer parece funcionar bien, asi que solucionado.
