### ISSUE TITLE
Comunicados y noticias

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#115]
tenemos un apartado que se llama noticias exclusivas para socios en abierto. LE CAMBIAMOS EL NOMBRE, se llamará “Comunicados y noticias”.  Allí van esas cartas, todas, las que desde secretaría se mandan a los socios. En abierto, sin login.

**Comment by muihlinn** [comment]
Tienen un apartado abierto en observatorio que se llama "comunicados, informes y acciones del IAC" que parece exactamente esto.

Tienen otro apartado para socios que se llama comunicados donde irá lo que quieran ponerles.

¿hay uno nuevo? ¿dónde íría?

**Comment by aitormendez** [comment]
Bien preguntado. Yo he entendido que se renombra el "comunicados" a "Comunicados y noticias", pero voy a asegurarme.

**Comment by aitormendez** [comment]
Vale, ya está claro. Era un comentario antiguo que me reenviaron sin fecha, por tanto, olvidamos. Cierro el issue porque ya está especificado en los criterios de discriminación lo que hay que hacer.
