### ISSUE TITLE
Consulta sobre PDFs

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#116]
Este comentario de Marina:
> Los pdf tienen que poder leerse con un lector, no solo descargarse, imagino que está por hacer. Y habíamos hablado de que los documentos iac también se pudieran leer en texto directamente en la página, debajo del título. Eso lo prefiere casi todo el mundo. En el caso del documento de buenas prácticas, el iac tiene colgado un escaneado, pero aquí lo tenéis bien legible:
> http://www.mcu.es/museos/docs/museosbuenaspracticas.pdf

Lo pongo aquí para acordarme, pero me gustaría comentarlo por teléfono. Yo hablé con Marina por teléfono de este tema hace unos meses y le dije que eso dependía del ordenador de cada uno. No obstante, quiero consultarlo contigo.

**Comment by muihlinn** [comment]
Tengo que mirarlo.

**Comment by muihlinn** [comment]
terminado
