### ISSUE TITLE
Prensa > noticias

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#117]
Las plantilla de la sección noticias no es compatible con las secciones que tienen documentos asociados.

Al estar prensa ahora dentro de noticias, no puedo traerme la plantilla directamente y la de noticias no lo contempla. Para la portadilla, la individual no creo que sea un problema. Bueno, en realidad no lo tengo claro, habrá que verlo.

**Comment by muihlinn** [comment]
Lo que se necesita:
- Revisar la plantilla de prensa para la portadilla (incluir o no la banda de adjuntos)
- Plantilla de página individual adaptada para aparecer en noticias.

Ahora las entradas de prensa, y en general, todas los que son ficheros adjuntos van a  tener todo el texto en la misma entrada. En la forma actual sólo muestra una entradilla. 

Puedes ver un ejemplo de prensa aquí:

http://iac.imaginarymagnitude.net/noticias/el-iac-prensa/asociaciones-piden-concurso-musac-razon-20012009.html

y un ejemplo de Documento aquí:

http://iac.imaginarymagnitude.net/documentos/medidas-apoyo-sector-arte-espana.html

Imagino que la banda con los adjuntos deberá ir o bien bajo el título o bien como está bajo la entradilla para no acabar demasiado abajo. El texto extendido necesita marcado para tener un formato acorde.  El problema es que la estructura del html entre noticias y prensa no es compatible.

**Comment by aitormendez** [comment]
Estoy pendiente de una respuesta del cliente para saber qué hacemos con este tema de los documentos. Les mandé un email y hablé con Jorge por teléfono. Me dijo que lo dejáramos para el final. ¿Podemos dejarlo de momento con la entradilla hasta que se definan? Dejo el issue abierto.

**Comment by aitormendez** [comment]
Necesito una explicación sobre esto: "Plantilla de página individual adaptada para aparecer en noticias."
¿Qué es una página individual?

**Comment by muihlinn** [comment]
donde se visualiza la entrada del documento, al hacer click en una portadilla, por ejemplo:

<http://iac.imaginarymagnitude.net/documentos/medidas-apoyo-sector-arte-espana.html>

**Comment by aitormendez** [comment]
Sigo teniendo dudas al respecto de la portadilla de noticias. El marcado actual es:
```html

<article class="noticia-portada">
	<aside class="metadato">
		Publicado en<b><a href="#">seccion</a></b>el<b>10-02-2016</b>
	</aside>
	<h1>Titular</h1>
	<p>Entradilla</p>
	<a class="leer" href="#">Leer más</a>
  </article>
```

Y este es exactamente el marcado que tienes que usar para prensa en la portadilla. Es decir, yo no puedo hacer nada más, sólo decirte qué marcado lleva pero tú tienes que implementarlo. Por eso, después de revisarlo a la luz de la conversación contigo creo que yo no juego ningún papel en este proceso. Tú dirás.

**Comment by muihlinn** [comment]
Exactamente así es como está hecho desde antes de poner este issue, aunque no estoy seguro de cómo se trata lo del `<p>`.

Trataré de explicarme más claramente. Lo que se necesita es que consideres con respecto a la portadilla de noticias y el diseño es:

- La conveniencia (o no) de que aparezca la banda de descargas como lo hace en las otras portadillas de entradas con adjuntos 
- En caso afirmativo, con qué marcado, que bien puede con el mismo que tiene en esas otras secciones, pero con `div.adjuntos` funcionando correctamente en este otro contexto de `article`en lugar de `ul.docs>li.doc`de documentos.

Con respecto a la página individual de prensa (que en parte afectará al resto de secciones de adjuntos), lo que se hace es aislar el `li.docs` de la entrada de la portadilla de documentos, y lo que habrá que hacer es:

- Ponerle el soporte del texto extendido
- Asegurarse de que el `aside.metadato` funciona correctamente en el contexto
- Cambiar la posición de la banda de descargas `div.adjuntos`, como hemos hablado esta mañana.

**Comment by aitormendez** [comment]
No ponemos el adjunto en la portadilla.

Por favor, no me mezcles issues. Aquí lo de la portadila, en el de la noticia individual lo suyo porque ya está resuelto.
