### ISSUE TITLE
Plantilla documentos

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#118]
ver #117 

Es básicamente lo mismo que el issue #117 pero sin tener en cuenta las peculiaridades de noticias.

- Repensar la posición de la barra de adjuntos.
- Necesita soporte para texto extendido

**Comment by aitormendez** [comment]
Este es el commit: eaa279abfae2041c9f6791cd02c6206bfbf941e6
Pero en lo que a ti respecta sólo tienes que cambiar el html:
https://github.com/aitormendez/iac-web/blob/master/_noticia-prensa.html#L39-L41
