### ISSUE TITLE
@media print

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#12]
Luis, necesito que me confirmes la forma de resolver la plantilla para imprimir el PDF. Hay dos posibilidades (yo prefiero la primera).
- Utilizar una plantilla HTML distinta a la página de referencia
- Utilizar la misma plantilla modificando el CSS con @media print

**Comment by muihlinn** [comment]
Prefiero la plantilla.
Cre�a que te lo hab�a dicho, pero igual no.

On 15/10/2015, at 16:04, Aitor M�ndez wrote:

> Luis, necesito que me confirmes la forma de resolver la plantilla para imprimir el PDF. Hay dos posibilidades (yo prefiero la primera).
> - Utilizar una plantilla HTML distinta a la p�gina de referencia
> - Utilizar la misma plantilla modificando el CSS con @media print
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/aitormendez/iac-web/issues/12



I feel better, to hell with photography, art, women, and all
E. Weston, 1924
-----------------------------------------------------------------------
http://luis.imaginarymagnitude.net/
