### ISSUE TITLE
Trasladar al head la llamada del JS a ckeditor

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#14]
Yo lo he hecho en el repo, para que lo hagas en lo tuyo.

**Comment by aitormendez** [comment]
6fcc142c21c4b6ca50829b64ffff844dfa3894af

**Comment by muihlinn** [comment]
Ok, va a quedar pendiente hasta que vea dónde lo vas a cargar, porque no se necesita en todas las páginas.

**Comment by muihlinn** [comment]
No es necesario trasladarlo, las páginas funcionan correctamente sin necesidad de moverlo.
