### ISSUE TITLE
CSS paginadores

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#19]
![screenshot 2015-10-20 12 42 52](https://cloud.githubusercontent.com/assets/7160350/10604941/370b82e6-7728-11e5-989d-d2e4df9bc5bb.png)

**Comment by aitormendez** [comment]
360409469833a8ebcf98a700152781d17e2b34d5

**Comment by aitormendez** [comment]
Corregido, ciérralo tú cuando lo integres

**Comment by muihlinn** [comment]
La página activa no se genera como un enlace, y se descoloca con lo que has pasado.

El código, generado es este:
`<li class="active">1</li>`
y se ve así:
![screenshot 2015-10-20 23 24 05](https://cloud.githubusercontent.com/assets/7160350/10621543/b76bfafc-7781-11e5-954d-21ab9ca3d0b0.png)

**Comment by aitormendez** [comment]
Confirmame que este es el contexto:

<ul class="pagination">
				    <li aria-label="Previous">
				        <span class="icon-izquierda-20" aria-hidden="true"></span>
				    </li>
				    <li>1</li>
				    <li class="active">2</li>
				    <li>3</li>
				    <li>4</li>
				    <li>5</li>
				    <li aria-label="Next">
				        <span class="icon-derecha-20" aria-hidden="true"></span>
				    </li>
				  </ul>

**Comment by aitormendez** [comment]
He hecho la corrección sobre esa estructura
16b57f91a7de03f20e29458bb358e6af8639d1be

**Comment by muihlinn** [comment]
```html
<nav>
  <ul class="pagination">
    <li><a href="#"><span class="icon-izquierda-20" aria-hidden="true"></span></a></li> 
    <li class="active">1</li>
    <li><a href="http://iac/noticias.html/?page=2">2</a></li>
    <li><a href="http://iac/noticias.html/?page=3">3</a></li> 
    <li><a href="http://iac/noticias.html/?page=2" rel="next">
      <span class="icon-derecha-20" aria-hidden="true"></span></a>
    </li>
  </ul>
</nav>
```
Tuve que tocar los presenters para modificarlo como me lo diste y es un follón del que probablemente se me habrá pasado alguna cosa; por defecto es compatible con los de bootstrap: http://getbootstrap.com/components/#pagination.

Por cierto, que –en teoría – la flecha correspondiente debería desactivarse en los extremos del paginador, como hace el paginador por defecto

El código que está generando ahora está –además- en:
https://gist.github.com/muihlinn/c5f3c76a0ea8204e6bd7

**Comment by muihlinn** [comment]
A modo de chanza, sobre https://github.com/aitormendez/iac-web/commit/16b57f91a7de03f20e29458bb358e6af8639d1be

![screenshot 2015-10-21 09 51 27](https://cloud.githubusercontent.com/assets/7160350/10630746/653b0b08-77d9-11e5-8ec7-c05a0def3a9e.png)

**Comment by aitormendez** [comment]
Joder, luis, llevo una hora para eliminar las etiquetas de enlace y ahora el código que generas tiene etiquetas der enlace. Hablemos, por favor

**Comment by aitormendez** [comment]
Ah, me acabo de dar cuenta que sólo tenía que modificar la página activa, mierda.

**Comment by muihlinn** [comment]
:dart:

**Comment by aitormendez** [comment]
Hecho c37af9addf16fdfdb48a40ce79c9e5d93e987e3c

**Comment by muihlinn** [comment]
funcionando.
