### ISSUE TITLE
Entradilla paginas.

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#21]
La entradilla no tiene un límite formal de un párrafo, igual esto es buscado, confirmar.

![screenshot 2015-10-23 18 57 02](https://cloud.githubusercontent.com/assets/7160350/10699578/04bed7c4-79b8-11e5-97a7-a04b2ad5a2ca.png)

**Comment by aitormendez** [comment]
No, me lo apunto. Hay que poner el elemento ::after en un p last-child

**Comment by muihlinn** [comment]
y no seria mejor una propiedad de .entradilla? imagina que ponen una imagen como último elemento.

**Comment by aitormendez** [comment]
sí, mejor.

Aitor Méndez
-
(+34) 620552774
Skype: aitor.mendez

**Comment by aitormendez** [comment]
7329ba952731b384eb9959834a5b5891fd373740
