### ISSUE TITLE
Nueva estructura docs y noticia individual

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#27]
Luis, tienes que cambiar unas clsases en el DOM de documentos y noticias:

Donde pone `col-izquierda`, debe poner `col-izquierda-b`.
Donde pone `col-centro`, debe poner `col-centro-b`.
Donde pone `col-derecha`, debe poner `col-derecha-b`.

84f3851b7f3d15c5f27f544bd67f07ed88b53767

**Comment by muihlinn** [comment]
queda pendiente el div para las imagenes en el cuerpo de la noticia.

**Comment by aitormendez** [comment]
¿Te refieres a este issue?
https://github.com/aitormendez/iac-web/issues/16

**Comment by muihlinn** [comment]
no, ese es parecido, y la solución será básicamente la misma, pero el issue es diferente.
