### ISSUE TITLE
div de imagenes re: #27

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#28]
ver commit  53dc871

**Comment by aitormendez** [comment]
Ah, sí, es que le subí el lapso de tiempo porque no me dejaba trabajar en el diseño. Como tiene que ser 10 segundos, ponlo en 10000 ms.

**Comment by muihlinn** [comment]
Es una nota para mí, de todas formas corrijo lo tuyo

**Comment by muihlinn** [comment]
El asunto del carrusel está resuelto, pendiente lo de CKEditor. Se abre nuevo issue
