### ISSUE TITLE
Plantilla para PDF v.1

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#29]
3dee69887a25241203d30020b64dac287f8a6fc1

**Comment by aitormendez** [comment]
Cuando lo pruebes pásame el PDF a ver cómo queda, please.

**Comment by muihlinn** [comment]
¿convendría que en algún sitio apareciese el permalink? 

Dame unos minutos, que estoy cerrando otras cosas

**Comment by muihlinn** [comment]
asegúrate de que no metes el .DS_Store en el commit, o tenemos conficto seguro :(

**Comment by aitormendez** [comment]
En principio no lo veo. Sería útil para imprimir, pero si el usuario le da a imprimir normal, se le imprimirá la plantilla normal, con lo que siempre tendré que hacer un CSS media print, así que, creo que no.

Tranqui, yo tengo que salir media hora.

Pero el .ds store no estaba en el gitignore?

**Comment by muihlinn** [comment]
Debería, pero por si acaso fijate en lo tienes en Stage antes de un commit.

**Comment by aitormendez** [comment]
esque siempre utilizo `git add .` Es un problema gordo si no puedo hacerlo porque lo tengo que hacer muchas veces.

**Comment by muihlinn** [comment]
Después de investigar un buen rato los errores que me daba, generando un pdf plano, sin ninguna tipografia, he resuelto la mayoría de los problemas, pero partes del pdf parece que se salen de los límites. 

Creo que la solución más simple  es generar un css propio simplificado que evite cargar todas las propiedades CSS3 que no se necesitan, y que probablemente estén implicadas.

BTW: ¿qué media hay que utilizar?

PS: si quieres mirar la documentacion es dompdf : http://pxd.me/dompdf/

[f492a90216b2efdf86649345b62746ce.pdf](https://github.com/aitormendez/iac-web/files/21620/f492a90216b2efdf86649345b62746ce.pdf)

**Comment by aitormendez** [comment]
Ya lo he visto. Lo mejor es que hablemos.

**Comment by aitormendez** [comment]
Ya está. He tardado bastate porque he tenido que compilar el less de las fuentes para el logotipo de la cabecera i concatenarlo al pdf.css
e2cae9f3d6356dbbf793c2ec5d355a9d720f8cbb
míralo y me cuentas.

**Comment by muihlinn** [comment]
Mejor, pero aún tiene problemas.

- El logo aparece
- El texto del logo va mal, aparece, aunque las letras aparecen escritas encima de ellas mismas.
- Al metadato le ocurre algo parecido
- los subrayados de los enlaces salen casi como strike
- las negritas siguen apareciendo en helvética, esto parece que es porque no hay un `@font-face` que llame a Asap bold, y cae en helvética. Modifiqué el fichero de configuración de fuentes de duplicando la entrada de Asap en la tag bold y aparecen bien, pero no en negrita.

[f492a90216b2efdf86649345b62746ce.pdf](https://github.com/aitormendez/iac-web/files/22050/f492a90216b2efdf86649345b62746ce.pdf)

**Comment by aitormendez** [comment]
Pásame los warnings

**Comment by muihlinn** [comment]
no me da warnings.

**Comment by aitormendez** [comment]
Prueba ahora, que he incluido un reset al principio del css

**Comment by muihlinn** [comment]
Igual, el problema sigue siendo que no hay un tipo asociado a bold para 'asap', y cae en helvética que es la que lo tiene
```php
<?php return array (
  'sans-serif' => 
  array (
    'normal' => DOMPDF_DIR . '/lib/fonts/Helvetica',
    'bold' => DOMPDF_DIR . '/lib/fonts/Helvetica-Bold',
    'italic' => DOMPDF_DIR . '/lib/fonts/Helvetica-Oblique',
    'bold_italic' => DOMPDF_DIR . '/lib/fonts/Helvetica-BoldOblique',
  ),
  'times' => 
  array (
    'normal' => DOMPDF_DIR . '/lib/fonts/Times-Roman',
    'bold' => DOMPDF_DIR . '/lib/fonts/Times-Bold',
    'italic' => DOMPDF_DIR . '/lib/fonts/Times-Italic',
    'bold_italic' => DOMPDF_DIR . '/lib/fonts/Times-BoldItalic',
  ),
  /** Otras configuraciones omitidas */
  'homenaje' => 
  array (
    'normal' => DOMPDF_FONT_DIR . '43a2131b8f13d9e7fc14841400ef2303',
  ),
  'asap' => 
  array (
    'normal' => DOMPDF_FONT_DIR . '4e9fe65091fa2510bebf503afd517cdc',
  ),
) ?>
```

**Comment by aitormendez** [comment]
Ya he visto el problema. Prueba ahora, las negritas deberían funcionar.

1aa98fcd05afb07a542533bbc729e06cec0f48a4

**Comment by muihlinn** [comment]
Se generan itálicas pero no negritas.
Creo que lo que necesita es que se lo den muy mascadito.

```php
  'asap' => 
  array (
    'normal' => DOMPDF_FONT_DIR . '4e9fe65091fa2510bebf503afd517cdc',
    'italic' => DOMPDF_FONT_DIR . 'b8099c8f647eb4652ca0aca057dd8371',
  ),
```

**Comment by muihlinn** [comment]
Mírate estos dos, en lo que a tí concierne se trata de definir el font face con el font-style y el font-weight que corresponda. Si con eso no lo coge, veremos de instalar la tipografía.

https://github.com/dompdf/dompdf/issues/784#issuecomment-35222645
http://stackoverflow.com/questions/24412203/dompdf-and-set-different-font-family

**Comment by aitormendez** [comment]
Llevo todo el finde intentano y finalmente he conseguido un plugin de grunt que funciona para convertir las fuentes. Todo el sistema de nombrado es distinto. Aunque sigue usando la nomenclatura numérica, ahora el identificador de peso se inclulle en el nombre del archivo de cada fuente. Por ejemplo, "Asap-400.ttf".

A ver si funciona. f22121a7db5d5b8b22cbb2aa68697b9afccd31b3

**Comment by aitormendez** [comment]
Cierro lo del pdf
