### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#3]
Tenemos favicon en esta última? 
Antes teniamos esta tag en el head:

`<link rel="shortcut icon" href="dist/img/favicon.ico">`

**Comment by aitormendez** [comment]
De momento no, aunque habrá que hacerlo. Por eso la he quitado. También porque había dos lineas distintas en referencia al favicon, y no sé por qué. Parecían duplicadas.  Las he quitado hasta que mire cómo se hace, pero si tú lo sabes, adelante ;)
