### ISSUE TITLE
Mensaje sin contenido en portadilla noticias

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#31]
Cuando no hay contenido en alguna categoria (noticias) se genera este mensaje
```html
<main class="col-centro-b">
Lo sentimos, aún no hay contenido para este apartado
<aside> </aside>
</main>
```
Quizás habría que mejorar el formato.

![screenshot 2015-10-27 20 09 57](https://cloud.githubusercontent.com/assets/7160350/10769560/01ea9ba0-7ce7-11e5-96ac-7ecf042f625e.png)

**Comment by aitormendez** [comment]
me lo adjudico

**Comment by muihlinn** [comment]
dentro de `<main>` se le puede poner marcaje adicional sin problema.

**Comment by aitormendez** [comment]
1119c9f482c8d75543ea562766b1b35712a9496f
