### ISSUE TITLE
Habilitar comentarios en editoriales

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#33]

**Comment by aitormendez** [comment]
Luis, lo mejor para hacer esto es ver el output que te da el backend, y me adapto ¿no?

**Comment by muihlinn** [comment]
No da ninguno, aún.
Precisamente esperaba el front para hacerlo.
Pero vaya, lo de siempre, los campos habituales, y clases genéricas dentro del envoltorio.

**Comment by aitormendez** [comment]
Como me dijiste que lo harías con un plugin de Laravel, he supuesto que te dará una salida predefinida, pero tengo que saber cómo es, si tiene comentarios anidados o cualquier otra característica. Si me dices que no, me lo invento yo.

**Comment by muihlinn** [comment]
Vale, lo haces a tu aire.

Si hay que saber si comenta cualquiera, sólo socios, o qué .
O si tienen que esperar a que un administrador los apruebe o aparecen tal cual

**Comment by aitormendez** [comment]
Luis, los comentarios, a petición del cliente, moderados y sólo para socios. Es decir, hay que loguearse para comentar.

**Comment by aitormendez** [comment]
Ya está la estructura para los comentarios. Tengo que darle estilo, pero puedes trabajar con esto. Quizá te añada una clase o dos más adelante, pero nada más.
https://github.com/aitormendez/iac-web/blob/master/_editorial.html#L18-L72

**Comment by aitormendez** [comment]
Ya está terminado.
https://github.com/aitormendez/iac-web/blob/master/_editorial.html#L20-L89
Aquí ves cómo queda:
http://iac.e451.net/editorial.html

**Comment by muihlinn** [comment]
Perfecto, al tener que estar el usuario dado de alta e identificado en el sistema para poder comentar los campos de nombre y email no eran necesarios, ya que se cojen del perfil, pero me va bien así.
