### ISSUE TITLE
Seccion Documentos

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#34]

**Comment by aitormendez** [comment]
Aprobado por Marina.

1. Los documentos no utilizan el mecanismo de generar PDF, son adjuntos simplemente.
2. Los documentos están categorizados por ellos, es decir, ponen y quitan las que quieren. Las categorías (o etiquetas, lo que tú veas), se ordenan en el lateral como una lista de checkboxes y actúan como filtros.
3. Todos los documentos mostrados aparecen en orden cronológico.
4. La estructura de la entrada sería:
* Título de la entrada (que será el título del documento).
* Pequeña descripción (opcional).
* Botón descarga archivo PDF adjunto.

**Comment by aitormendez** [comment]
Hay que resolver la navegación por categorías para versiuón móvil.

**Comment by aitormendez** [comment]
Este issue no sé por qué lo dejé abirerto. Está listo, no?

**Comment by muihlinn** [comment]
no, estoy en ello, lo que no hiciste fue cambiarme a mí.
