### ISSUE TITLE
Redes sociales

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#35]

**Comment by aitormendez** [comment]
Llevo toda la tarde leyendo y creo que con mi nivel de conocimiento noi puedo hacer yo el código, así que he recurrido a un servicio externo. Aunque me falta darle un poco de estilo ¿puedes probar a ver si funciona?

d52769168c99414eb151fd1b2c1a969c703fbcd6

**Comment by muihlinn** [comment]
Tengo que verlo

**Comment by aitormendez** [comment]
OJO, sale una ventana emergente de forma automática. Hay que quitarla.

**Comment by muihlinn** [comment]
Esto va en las páginas individuales, ¿en alguna más?

**Comment by muihlinn** [comment]
No tengo claro dónde colocarlo en las páginas individuales que no tienen un `aside.col-derecha-b`como son las individuales de prensa o documentos

**Comment by aitormendez** [comment]
creo que ahí puedes poner la col-derecha-b entera sin más, tal cual está aquí:
https://github.com/aitormendez/iac-web/blob/master/_que-es.html#L105-L114

**Comment by muihlinn** [comment]
hecho.
