### ISSUE TITLE
h3.ariadna > a [ color erroneo ] en los listados.

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#38]
Quedamos que las etiquetas de los listados completos iban a ser un enlace al listado completo
– si el `a` engloba al `h3`el color es correcto pero se sangra con respecto al listado

![screenshot 2015-10-28 18 55 29](https://cloud.githubusercontent.com/assets/7160350/10798079/15f116fa-7da6-11e5-8df0-4215b74f9267.png)

– Si el `a`está dentro del `h3`se alinea correctamente, pero el color del enlace es erroneo.
![screenshot 2015-10-28 18 55 41](https://cloud.githubusercontent.com/assets/7160350/10798115/4505f42e-7da6-11e5-9f96-baca9c0746de.png)

**Comment by aitormendez** [comment]
Pues espérate porque Marina quiere eliminar la portadilla de noticias. Le he escrito un email para confirmar.

**Comment by aitormendez** [comment]
Hecho
f93eb5e085cc74a7492be5ceed49fe2c5720bbc0

**Comment by muihlinn** [comment]
Ya está integrado, no lo cierro porque la primera vez que pasas sobre la etiqueta en chrome hay un pequeño desplazamiento. Míralo y lo cierras tú.

**Comment by aitormendez** [comment]
Ya está arreglado. No me gusta nada cómo renderiza chrome...
3cff16d58522df76bbd6517f1a1cedf7ca473557
