### ISSUE TITLE
Nueva estructura archivos less

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#41]
He tardado tres horas en resolver el problema que detectamos ayer, donde se descolocaban muchas cosas que ya estaban hechas. Lo he resuelto, pero también he decidido reestructurar los archivos less , separándolos en ficheros pequeños para tener un control de rendimiento más preciso. Ahora están en un directorio que se llama less-iac.

Sólo para que lo sepas. Puedes cerrar el issue cuando lo veas.
6c839c5b444c99effe32581761feaf6a149a8666

El gruntfile está actualizado para la nueva estructura.

**Comment by muihlinn** [comment]
Visto, lo cerraré luego cuando ya lo dé por integrado.
He decidido cambiar todo el sistema de categorías a una librería en lugar del mío propio, porque con tanto cambio – o tentativa de cambio – me llevaba más tiempo de mantenimiento de éstas que usar uno nuevo. Estoy un poco desconectado porque requiere bastante concentración, pero mantengo la línea abierta.

**Comment by aitormendez** [comment]
Ok, yo estoy igual.
