### ISSUE TITLE
h-card

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#43]
Estoy haciendo las listas de socios con microformatos h-card, Una peregunta, ¿Tienes separados nombre y apelido en la base de datos?

d835d9f4cde8c374566ce18a9b1cabdad81bfc61
http://microformats.org/wiki/h-card

**Comment by aitormendez** [comment]
Otra pregunta relacionada. Fíjate en la linea 41

https://github.com/aitormendez/iac-web/commit/d835d9f4cde8c374566ce18a9b1cabdad81bfc61#diff-84d6a08b0992db45f0976feaa292439fR45

El email ¿debería ir aquí visible? Se supone que la etiqueta de microformato parta email es un email. O qué forma de mandar el email habría que utilizar? ¿Qué opinas?

**Comment by muihlinn** [comment]
Sí, están separados nombre y apellidos.

Isabel me dijo por teléfono que los emails no deben ser visibles porque se les complicaría legalmente.
Sólo se usa como identificador y para poder contactar con el asociado (con un formulario), pero sin ser visible

**Comment by aitormendez** [comment]
ok, entonces, ¿qué hacemos con el email? Lo único que se me ocurre es quitarle la etiqueta semántica al enlace "contacto" y que se abra la solapa del emai con JS.

**Comment by muihlinn** [comment]
pues eso o que no aparezca, no le veo mucha más solución.
