### ISSUE TITLE
Estructura para grupos de trabajo

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#44]
Confirmada por Marina en email del 5 de noviembre:

- Componentes (miembros)
- Objetivos
- Email del jefe de grupo

Habrá que distinguir un jefe en la base de datos, pera que aparezca su email.

**Comment by muihlinn** [comment]
reenvíame el email, pls

**Comment by aitormendez** [comment]
Ya está el front
82a81452165850a796985bf39e680367b38e2226
A validar por Marina
