### ISSUE TITLE
Grupos, clases genéricas en la declaración

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#47]
Actualmente cada párrafo de declaración tiene asignada una clase, y sería mejor para no tener que manipular el contenido del campo a posteriori que el elemento superior contuviera la defición de `p.declaracion` ya sea el mismo `header` o un envoltorio.

**Comment by aitormendez** [comment]
No veo que la declaración que tenga clases en los párrafos ¿dónde lo has visto?
https://github.com/aitormendez/iac-web/blob/master/_perfil.html#L20

**Comment by muihlinn** [comment]
En todas las páginas de grupo
```html
<main>
	<article>
		<header>
			<h1><a href="grupo-territorial.html">Castilla-León</a></h1>
			<p class="declaracion">Suspendisse accumsan ligula eu porttitor ornare. Vestibulum tempus tincidunt erat sit amet convallis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Morbi at felis dui. Pellentesque tincidunt, nulla ut scelerisque dignissim, mi enim tincidunt</p>
```

**Comment by aitormendez** [comment]
Elimina la clase, sin más

**Comment by aitormendez** [comment]
Ojo, hay que quitarlo en grupos de trabajo y consejo territorial.
34335f27dae598a7042595f4c7cd9fa4195932d0
