### ISSUE TITLE
ariadna grupos. A dónde apunta la etiqueta IAC en este caso?

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#48]
pues eso, ¿cuál sería la portadilla del listado de grupos? ¿tiene?

**Comment by aitormendez** [comment]
Ya está resuelto. Ojo, los elementos `.ariadna` que no llevan el texto dentro de un enlace `a` deben llevar un `span`.
https://github.com/aitormendez/iac-web/commit/64bd19bef836b58a3f655fa69ef7025ed2ed020d#diff-eece8bb51812c6b0acd299dbdd0688e5R5
