### ISSUE TITLE
botones => input type submit en las pestañas

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#5]
El css falla donde son button en lugar de input type. 
El botón es mucho más grande

**Comment by aitormendez** [comment]
Dime un ejemplo, yo los veo bien.

**Comment by muihlinn** [comment]
En la web ya implementada. Cuando la suba será más fácil ver estas cosas.

https://www.dropbox.com/s/njsejf2yyln30yl/Screenshot%202015-10-13%2013.15.42.png

**Comment by aitormendez** [comment]
Luis, se ha borrado el archivo de ejemplo del dropbox

**Comment by muihlinn** [comment]
Me temo que la captura es irrecuperable ya.
pero los botones esos los tienes como button y tienen que ser `<input type="submit" (...)>`

**Comment by aitormendez** [comment]
Oye, si sólo es cambiar el button por input, pregunto, ¿puedes hacerlo directamente?

**Comment by aitormendez** [comment]
Bueno, ya lo he hecho yo:
5fe7b5e699aeb8eac086b67faad26bccbfda8fd5

**Comment by muihlinn** [comment]
El transfondo de este issue no es cambiar directamente una cosa por otra, que ya estaba hecha desde antes de crearlo, sino asegurarse de que el estilo que se le aplica es el que le corresponde al elemento (incluyendo los otros posibles estados del elemento).

**Comment by aitormendez** [comment]
Ya me he asegurado. Cierro. Si por cualquier cosa ves que no se ve bien, lo vuelves a abrir.
