### ISSUE TITLE
Navegación "quiénes somos"

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#50]
Luis, me estoy dando cuenta de que el enfoque de navegaciíon para la parte de quiénes somos, no es muy bueno, porque las pestañas no permiten enlazar el contenido concreto de una de ellas. ¿Hay posibilidad de que cambie la navegación a enlaces simples, en lugar de pestañas, sin descalabrarte mucho?

**Comment by muihlinn** [comment]
no entiendo qué parte es la que quieres cambiar

**Comment by aitormendez** [comment]
Quiero sustituir la navegación de pestañas JS por una navegación de enlaces simples.
fíjate cómo está ahora: http://iac.e451.net/quienes-somos.html

**Comment by muihlinn** [comment]
explicamelo mejor por skype.
