### ISSUE TITLE
Pull conflicts

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#51]
Tengo prácticamente siempre conflictos al tratar de hacer un pull del repositorio, lo que resulta un poco molesto, ya que lo tengo automatizado :)

- Por un lado un .DS_Store aparece de cuando en cuando en cuando, aunque se supone que está en el .ignore
- Por otro, parece ser que está siguiendo parte del directorio bootstrap/dist

Lo investigo y cuando lo solucione hago un pull request.

**Comment by aitormendez** [comment]
el gitignore parece que tiene las dos cosas
```
*~
\#*\#
.#*
_err.*
.DS_Store
…/DS_Store
ckeditor/**
jquery/**
bootstrap/dist/**
```

**Comment by muihlinn** [comment]
por eso hay que verlo

On 23/11/2015, at 12:27, Aitor M�ndez wrote:

> el gitignore parece que tiene las dos cosas



I feel better, to hell with photography, art, women, and all
E. Weston, 1924
-----------------------------------------------------------------------
http://luis.imaginarymagnitude.net/

**Comment by muihlinn** [comment]
Al parecer si alguna vez estuvo en el repositorio seguirá apareciendo y dando algún problema en el futuro.

La solución la cuentan aqui:

http://stackoverflow.com/questions/1818895/keep-ignored-files-out-of-git-status
