### ISSUE TITLE
Plantilla individual de documentos ?

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#56]
tienen? es la página individual? 
deben ir? 
dónde está el enlace en el listado de documentos?

RE: #34

**Comment by aitormendez** [comment]
No lo había pensado pero, sí, deberían tener.

**Comment by muihlinn** [comment]
A este respecto hay que resolver visualmente dónde y cómo se ponen los documentos adjuntos en la plantilla individual. El resto será igual que noticias, por ejemplo.

**Comment by aitormendez** [comment]
Como hemos hablado, el permalink del documento utilizará el mismo layout que el listado de documentos, pero simplificado (eliminando la paginación y el resto de documentos. O sea, sólo se ve un doc)

**Comment by muihlinn** [comment]
Entiendo que el enlace del listado a la plantilla será el titulo. 
Necesitará un estilo, si no es suficiente con el que aparezca por defecto.
El <legend> ahora contiene un enlace, como en la individual del grupo territorial.
![screen shot 2016-01-15 at 14 44 26](https://cloud.githubusercontent.com/assets/7160350/12354488/a4f6920c-bb96-11e5-9e22-44007bdbf97d.png)

Si te parece bien tal cual, cierra el issue
