### ISSUE TITLE
enlaces

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#57]
tienen página individual? qué plantilla usarían?
tienen algún tipo de comentario?
admitirían más de un enlace por entrada? (esto ya lo hace, aunque el enlace que se usa en el listado es el primero)

**Comment by aitormendez** [comment]
¿Te refieres a los enlaces de los perfiles? No veo sentido a que admitan más de un enlace por entrada y tampoco a que tengan una página individual.

**Comment by muihlinn** [comment]
Creo que se dijo en algún momento, aunque no puedo asegurarlo, que podría haber algún comentario al enlace (entradilla o cuerpo). Lo doy por cerrado y si lo ves necesario, lo reabres.
