### ISSUE TITLE
Plantilla de errores

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#58]
Modificar la que se usa ahora, ver en:
http://iac.imaginarymagnitude.net/fallido

**Comment by aitormendez** [comment]
¿Que te parece que hagamos? ¿Ponemos página no encontrada y un campo de búsqueda debajo?

**Comment by muihlinn** [comment]
Puede haber varios tipos de errores, aunque el más frecuente será el 404, lo que sería deseable es una plantilla generalista. Del estilo a lo que he puesto en la url esa, pero de acuerdo al diseño actual. búsquedas y alternativas ya tienen por todos los lados en la propia plantilla general, pienso.

**Comment by aitormendez** [comment]
37e0d208a623977c6b4b62417d0e56d63fde3f1e

**Comment by muihlinn** [comment]
Ok, tengo una pregunta. Cuando es un error "fatal", que no va a ningún lado está claro, pero cuando es info que se debe mostrar encima del contenido general, ¿cómo afecta los layouts?

Quiero decir, todo el contenido va en container-fluid, pero las alertas no. Si, por ejemplo, un formulario no valida, ¿cómo pongo el mensaje?.

**Comment by aitormendez** [comment]
Vale, lo que tienes que hacer es insertar esto entre la navegación y el contenido. Es decir, después de `.overlay-4` y antes de `.cointainer-principal`:

https://github.com/aitormendez/iac-web/blob/f972fb09d19f55b8c25c6ae517c2a7823e94822a/_error.html

**Comment by muihlinn** [comment]
Ok, tengo una pregunta. Cuando es un error "fatal", que no va a ningún lado está claro, pero cuando es info que se debe mostrar encima del contenido general, ¿cómo afecta los layouts?

Quiero decir, todo el contenido va en container-fluid, pero las alertas no. Si, por ejemplo, un formulario no valida, ¿cómo pongo el mensaje?.
