### ISSUE TITLE
Tarjetón de mantenimiento

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#59]
Tarjetón de site en mantenimiento, probablemente nada más que el logo y un texto.

**Comment by aitormendez** [comment]
O sea, ¿una página sin los menús ni nada?

**Comment by muihlinn** [comment]
exacto, una página de mantenimiento

**Comment by aitormendez** [comment]
78913014533bd33612e6e15a97e30eabc5eeb7b3
