### ISSUE TITLE
Listado de socios en centro de documentación

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#61]
Sólo tiene enlace a página de prefil si es pública. Si no, el nombre del socio solamente.

**Comment by aitormendez** [comment]
Es igual que los enlaces de investigación. Cuando no lleva enlace (si no hay página de perfil) va dentro de un span: 
https://github.com/aitormendez/iac-web/blob/master/_socios-iac.html#L16

**Comment by muihlinn** [comment]
aplicado
