### ISSUE TITLE
edición perfil: los campos de texto se ven dificilmente si no están seleccionados

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#64]
Ejemplo de dos campos con contenido.

![screen shot 2015-12-23 at 22 29 20](https://cloud.githubusercontent.com/assets/7160350/11985420/daa4134a-a9c4-11e5-8833-30d91d375024.png)

Hay bastantes inconsistencias en el interfaz de edición del perfil, y partes completas que si están no las encuentro. Iré tratando de arreglar lo posible con lo que tengo, y te iré diciendo.

**Comment by aitormendez** [comment]
Arreglado complilando less
