### ISSUE TITLE
Problema con paginaciones cortas y listados laterales

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#69]
Si la lista de entradas es más corta que las categorías de `nav.menu-lateral` el paginador se vuelve invasivo.

![screen shot 2016-01-16 at 22 29 26](https://cloud.githubusercontent.com/assets/7160350/12374620/28c85b1e-bca1-11e5-80b0-68c4d4409d1e.png)

**Comment by aitormendez** [comment]
Para tan pocos items no hace falta paginación, ¿no?

**Comment by muihlinn** [comment]
es la segunda página, si te fijas, creo que está a páginas de 10 o 15

**Comment by aitormendez** [comment]
Ya veo. He pensado en una solución. Te llamo para comentarla.

**Comment by muihlinn** [comment]
Estaré a eso de las 16:30 o 17

On the road

**Comment by aitormendez** [comment]
Aquí hay que poner el plugin de paginación sencillo (flechas adelante y atrás). Pásame el código y yo le doy estilo, es lo más fácil.

**Comment by aitormendez** [comment]
Como hemos hablado, se trata ahora de meter la paginación en su columna. Es cosa de CSS. así que me lo asigno.

**Comment by muihlinn** [comment]
Cierro porque ha quedado obsoleto con la implementación del infinite scroll.
Lo que hubiera que tocar en el CSS queda en los dos issues abiertos #102 y #103
