### ISSUE TITLE
Entradilla en páginas

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#7]
¿tienen algún estilo en concreto?

véase: http://www.iac.org.es/
vs:
![screenshot 2015-10-12 21 22 28](https://cloud.githubusercontent.com/assets/7160350/10440372/d575049c-713e-11e5-8d42-ddbc5d7d9b39.png)

**Comment by aitormendez** [comment]
Sí deberían

**Comment by muihlinn** [comment]
¿y dónde puedo verlo? para aplicarlo en la plantilla, se entiende

**Comment by aitormendez** [comment]
commit 5d37c511f1d4b83207dfa9cf5dacd2bc13e0aff3

**Comment by muihlinn** [comment]
Si está bien así, vuelve a cerrar el hilo.

`<header class="entradilla">	{!! $content->entradilla !!} </header>`

![screenshot 2015-10-15 17 46 00](https://cloud.githubusercontent.com/assets/7160350/10519115/afa7d7da-7364-11e5-9aec-c71622166603.png)

**Comment by aitormendez** [comment]
Era así, pero he cambiado los estilos. No te afecta al DOM, así que cierro igualmente.
