### ISSUE TITLE
Errores ahora se pega al menú superior

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#70]
Imagino que quitar el borde superior en el issue #63 ha tenido este efecto indeseado.

![screen shot 2016-01-17 at 12 10 19](https://cloud.githubusercontent.com/assets/7160350/12377162/569780e8-bd13-11e5-8943-5163a4d70eef.png)

**Comment by aitormendez** [comment]
Sí, voy a ver

**Comment by aitormendez** [comment]
Ya está, se arreglará compliando el css
