### ISSUE TITLE
Los botones de formulario al estar seleccionados menguan mucho.

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#72]
Hay un pequeño problema con (probablemente todos) los botones de los formularios, al utilizar el tabulador y tenerlo seleccionado como elemento activo quedan mucho menores que en su tamaño original. No sé si es buscado o un bug.

Este es el de unirse al iac, pero he visto este comportamiento en otros sitios.

![screen shot 2016-01-19 at 22 45 36](https://cloud.githubusercontent.com/assets/7160350/12433000/d4bdac12-befe-11e5-8f05-44285a069d2c.png)

**Comment by aitormendez** [comment]
Qué raro, a mí no me pasa. Lo reviso.

**Comment by muihlinn** [comment]
sólo ocurre al coger el foco moviéndose entre los campos/botones con el tabulador o si mantienes pulsado el botón del ratón sobre el mismo, si sólo haces click no se llega a apreciar

**Comment by aitormendez** [comment]
Ya lo veo
