### ISSUE TITLE
Necesito una clase para el bloque de errores de validación de formulario

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#73]
que reconozca `.error` visualmente diferente del cuerpo de la etiqueta.
Ahora mismo es un span suelto.

![screen shot 2016-01-20 at 00 04 27](https://cloud.githubusercontent.com/assets/7160350/12434838/9ad94d7a-bf09-11e5-88b5-7569f6c3e3c5.png)
 
PS: Tenía prevista una forma más genérica, pero no casa bien con la plantilla y esto, creo,  va a ser mucho más sencillo para ambos.

**Comment by aitormendez** [comment]
Dame una referencia del código, que no sé de qué me habals, please

**Comment by muihlinn** [comment]
En la plantilla tengo esto
```
	{{ trans('public-forms.ph_email_contacto') }}
	@if($errors->has('email')) 	<span class="error">{{ $errors->first('email') }} </span> @endif
	{!! Form::email('email', null,  ['class' => "form-control"]) !!}
```
de lo que se generaría esto otro en caso de error de validación:

```html
      E-mail <span class="error"> texto del error </span> 
      <input class="form-control" name="email" type="email">
```

necesito que ese span con esa clase (o un marcado alternativo) sean algo diferente como para que no pase desapercibido para el usuario que ha habido un error.

**Comment by aitormendez** [comment]
ok

**Comment by aitormendez** [comment]
Ya está. Usa `form-error`

`<span class="form-error"> texto del error </span>`
