### ISSUE TITLE
Cabeceras homogéneas

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#74]
@muihlinn Veo que hay que dar uniformidad a las cabeceras de todas las cosas, creo que esta estructura resuelve todos los casos:

> aside metadatos
> >h3 ariadna (con y sin enlace) /h3
>  >h4 (Título de sección si lo tiene) (con y sin enlace) /h4

>/aside

> h1 (Título de documento si lo tiene) /h1

> aside metadatos
>> (fecha de publicación)

>/aside

Si te parece bien, lo cambio para que esté igual en todas partes.

**Comment by aitormendez** [comment]
Y es semánticamente correcta

**Comment by muihlinn** [comment]
Por mí bien, dime cuando lo tengas para implementarlo.

**Comment by aitormendez** [comment]
Casi me vuelvo loco con esta tontería. Ya está:
https://github.com/aitormendez/iac-web/blob/master/_que-es.html#L4-L21

**Comment by muihlinn** [comment]
Hecho, pero échale un ojo a los listados de categorias,pueden necesitar un repaso de sus estilos:

![screen shot 2016-01-21 at 22 56 34](https://cloud.githubusercontent.com/assets/7160350/12495839/44ee6ea6-c092-11e5-98ee-defe431044ce.png)

Puedes verlo en http://iac.imaginarymagnitude.net/

**Comment by aitormendez** [comment]
lo veo bien
