### ISSUE TITLE
Personalizar CKEditor

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#76]
Voy anotando las cosas que necesito:
* Introducir salto de página para generar PDF (no visible en el HTML renderizado)
* Menú de estilos específicos para generar un índice de documento:
 * indice
* Posibilidad de OL con una clase distinta (para list-style-type: lower-alpha)

**Comment by muihlinn** [comment]
Sin haberlo visto me da la impresión de que todo va a ser pedirle mucho, por eso insistía yo en que se usara marcado estándar. De todas formas lo miraré cuando vaya liquidando asuntos

**Comment by aitormendez** [comment]
CKEditor tiene esa posibilidad de personalización, en Wordpress ees relativamente sencillo de implementar y, en relación al marcado estandar, no existe tal cosa, que yo sepa, como marcado estandar para encabezados jerárquicos alternativos, como los que se usarían en un índice

**Comment by aitormendez** [comment]
Lo del salto de página no sé si se puede hacer. Sería cosa del dompdf. Es para poder hacer una portada con el documento de los estatutos. Si ves que te complica, olvídalo ;)

**Comment by muihlinn** [comment]
Aitor: http://stackoverflow.com/questions/8723487/dompdf-page-break-if-element-is-exceeding-page-height
https://css-tricks.com/almanac/properties/p/page-break/

PS: Claro que se puede personalizar, lo que no sé es si lo vas a usar sólo tú :) Bromas aparte, mírate eso, obviamente se puede meter elemento editando la fuente, o probablemente añadiendo un botón, pero creo que sería mejor para esos casos concretos, si no son norma, meter un adjunto.

**Comment by aitormendez** [comment]
Ah, pues sí. No sabía que podíamos meter un adjunto. Es verdad que lo del índice, puede que no lo use nadie. Lo he simplificando a tope, sólo necesito una clase "indice" para meter en los h1, h2, h3, et.

**Comment by aitormendez** [comment]
Oye, estoy pensando que es un jaleo todo esto y que con el adjunto se soluciona todo. o sea, que eliminamoe el índice del html y pasamos del page break porque ya tenemos el adjunto para subir.

El lower alpha lo meteré yo a mano en el código como excepción.

Si estás de acuerdo cierro el issue ¿ok?

**Comment by muihlinn** [comment]
Bueno, se puede meter un adjunto... técnicamente, ya que estaba en la primera especificación que se hizo, y así lo implementé. Desde el interfaz administrativo cualquier entrada puede tener adjuntos.

Pero el interfaz público no muestra adjuntos más que en las secciones de documentos y prensa; el documento que aparece a la derecha es un PDF generado a partir del contenido de la entrada con el formato que se le pueda dar via DOM/CSS y que esté soportado por dompdf.

Esta implementación es válida para noticias, y observatorio que son básicamente notas de prensa (que no iban a querer tener que estar generando pdfs constantemente, y es menos válida para la página de los estatutos. Actas no he visto ninguna, pero creo que también les podría ir mejor pegar el texto del acta y añadir un adjunto del documento que no iban a redactar en la web (imagino). En cualquier caso es pensar en voz alta.
