### ISSUE TITLE
HTML 5 semántico en páginas

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#8]
Las páginas, como "qué es el IAC" también deberían incluir las tags semánticas para organizar el documento.

Por el momento he dispuesto la plantilla así [sólo la parte del contenido y de forma provisional] :
https://gist.github.com/muihlinn/ab7d7f409fcfb2fa106d

**Comment by aitormendez** [comment]
Es lo que había pensado, pero tenía la duda de si el aside puede estar dentroi de article. Si no, hay que envolver .col-izquierda (que tiene el título) y .col-centro (que tiene el grueso del contenido) en un <article>

**Comment by muihlinn** [comment]
Respuesta incompleta :(

**Comment by muihlinn** [comment]
Es correcto que esté dentro de article.
ver ejemplos en : http://www.w3.org/TR/html5/single-page.html#the-aside-element

**Comment by aitormendez** [comment]
commit 1f9e06133fa0e456b2d4753741e2ac2093ed7bba
