### ISSUE TITLE
Ocupación listado de socios

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#81]
IAC/ quiénes somos: que aparezca la ocupación da cada uno, además de en el perfil, ya directamente visible al lado del nombre.

**Comment by muihlinn** [comment]
Previsto en los listados de socios, modificadas las peticiones para incluirlo.
En el perfil no hay un espacio previsto para la ocupación.

**Comment by aitormendez** [comment]
Sólo añadir esta línea https://github.com/aitormendez/iac-web/blob/master/_quienes-somos.html#L189

**Comment by muihlinn** [comment]
Añadida la ocupación desde la base de datos, sin marcaje alguno

**Comment by muihlinn** [comment]
modificadas las plantillas
