### ISSUE TITLE
Modificar grupos de trabajo

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#85]
IAC/ grupos de trabajo: que los componentes vayan en letra más pequeña, como el texto. Y que no ponga componentes, sino como está en la web actual: coordinación donde ahora pone jefe de grupo, y debajo del coordinador o coordinadores aparecen sin más los nombres de los componentes.

**Comment by aitormendez** [comment]
grupos de trabajo: de nuevo, detrás de cada nombre, su actividad profesional

**Comment by aitormendez** [comment]
Hecho: 2607978b3a1a91652b319861280636bacbc5d054

**Comment by muihlinn** [comment]
Queda pendiente para segunda ronda que los usuarios sean socios del IAC, requiere reforma completa del sistema de grupos. Otra vez.
