### ISSUE TITLE
Contenidos presna

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#87]
IAC/ el IAC en la prensa: colgar al menos lo que hay en la web actual. Aunque está totalmente desactualizado, pero eso imagino que se irá llenado cuando vayáis adjudicando las noticias desordenadas a cada saco.

**Comment by muihlinn** [comment]
Prensa: hay lo que aparece al pinchar en el menú IAC en la prensa.
Pendiende de la importación de las cosas que estén sueltas en la BBDD
