### ISSUE TITLE
Contenido documentos

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#88]
Centro de documentación: colgar los documentos IAC, en enlaces poner sección en construcción, y en socios del IAC, por el momento, lo de añadir la actividad detrás de cada nombre.

**Comment by muihlinn** [comment]
- He colgado los documentos que aparecen en el enlace "documentos" de la web actual, a los que he añadido los estatutos actuales, imagino que en la bbdd habrá más (esto es algo que tengo que hablar con Marina). ** Excepto dos que son documentos de issuu, y documentos está pensado para tener adjuntos, no enlaces. ** :-/ 
- "En construcción" va en un h2.text-center en la plantilla
- Actividad de los socios, puesto, pendiente del estilo (o formato) que decidas.

**Comment by aitormendez** [comment]
Hecho: https://github.com/aitormendez/iac-web/blob/master/_socios-iac.html#L20-L25
