### ISSUE TITLE
Error semántico en los titulares de páginas

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#9]
Si no me equivoco es incorrecto tener un titular de mayor rango por debajo de uno de menor rango en la misma seccion [https://goo.gl/eJO9CV]. 
Teóricamente esto debería resolverse con una clase que no afectara a la estructura del documento.

https://gist.github.com/muihlinn/663b2527e1df649e738b

**Comment by aitormendez** [comment]
He estado mirando y parece que el breadcrumb hay que hacerlo con <ol>, también se poueden meter dentro de un .nav
https://coderwall.com/p/p0nvjw/creating-a-semantic-breadcrumb-using-html5-microdata

**Comment by muihlinn** [comment]
Este issue está relacionado con el #6, el caso es que no hay previsto ninguna manera de hacer un breadcrumb del contenido. Las secciones en las que se organiza internamente el contenido no son un calco exacto de los menús :-?

**Comment by muihlinn** [comment]
<aside class="seccion"> ?

**Comment by aitormendez** [comment]
¿Qué duda tienes?

**Comment by muihlinn** [comment]
Que no hemos quedado en nada

**Comment by aitormendez** [comment]
Si lo hablamos el otro día por teléfono y quedamos en poner el breadcrumb en un aside ¿no?

**Comment by aitormendez** [comment]
hecho

**Comment by aitormendez** [comment]
Luis, reabro esto porque veo que no está implementado. El ariadna debe ir siempre en un aside, tal como aparece aquí: https://github.com/aitormendez/iac-web/blob/master/_socios-iac.html#L3

**Comment by muihlinn** [comment]
Sólo había una plantilla, la de página que lo tenía de la forma antigua.
Lo he corregido, pero no lo he subido a ningún sitio visible.
