### ISSUE TITLE
Revisión general móvil viewport

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#94]
revisar todo

**Comment by muihlinn** [comment]
pásame el commit, por favor, que vea los diff.

**Comment by aitormendez** [comment]
¿esto por qué lo tienes asignado tú? Ya no me acuerdo.

**Comment by muihlinn** [comment]
no sé. yo tampoco, al parecer lo has hecho tú hace una hora. :-?

**Comment by aitormendez** [comment]
estoy fatal. lo cierro
