### ISSUE TITLE
Texto explicativo documentos

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#95]
Debe ir en un p
http://iac.imaginarymagnitude.net/centro-documentacion/documentos.html

**Comment by muihlinn** [comment]
no entiendo ¿qué hay que cambiar?

```html
<div class="col-centro-b">
  <main>
    <article>
      <header>	<h1>Consejo Territorial</h1>	</header>
      <p>El Consejo Territorial es (...).</p>
      <p>Los delegados (...).</p>
  </article>
 </main>
</div>
```

**Comment by aitormendez** [comment]
Me refiero a Documentos, como dice en el título, no al consejo territorial. Mira el marcado mío:
https://github.com/aitormendez/iac-web/blob/master/_biblioteca-de-documentos.html#L103-L106
que es como debe estar y luego compara cómo lo tienes tú, sin el elemento P, en el enlace que te he dado: http://iac.imaginarymagnitude.net/centro-documentacion/documentos.html

**Comment by muihlinn** [comment]
Perdón, me he confundido con lo de "texto explicativo".
Olvidé ponerles las marcas de párrafos al importarlo. Ya está solucionado, pero aún no está subido.
