### ISSUE TITLE
Cambiar clase en navegación lateral

### ISSUE THREAD

**Issue by aitormendez** [aitormendez/iac-web#97]
La clase de los items activos debe ser "activo", en lugar de "active"
https://github.com/aitormendez/iac-web/blob/master/_noticias.html#L10

**Comment by muihlinn** [comment]
Es `activo` en todos los listados de categorias laterales, excepto en quienes somos. 
Si lo cambio a `activo`queda de esta manera. Debe haber alguna sobrecarga o similar en less

![screen shot 2016-01-27 at 12 26 59](https://cloud.githubusercontent.com/assets/7160350/12612243/8aaae06a-c4f1-11e5-8973-55e158f590d1.png)

**Comment by aitormendez** [comment]
En mi web sale bien. Debe haber algún error en lo tuyo, pero con una captura no puedo saberlo. Tienes que hacerlo públicoo darme el código para que pueda mirarlo.

**Comment by muihlinn** [comment]
Aqui es el único sitio donde se usa `active`, si lo cambias con el inspector a `activo` sale como en la captura.

http://iac.imaginarymagnitude.net/quienes-somos/junta.html

**Comment by aitormendez** [comment]
Claro, el LI activo no tiene que tener dentro un elemento A. En los demás sitios sí lo has hecho bien.

**Comment by aitormendez** [comment]
Míralo aquí, por ejemplo: http://iac.imaginarymagnitude.net/noticias/actividades-socios
