### ISSUE TITLE
menu lateral, clase activo, noticias asignada a varias categorias

### ISSUE THREAD

**Issue by muihlinn** [aitormendez/iac-web#98]
`li.activo` es un `inline-block`, si el contenido tiene varias categorías asignadas, deja de ser una columna.
Ocurre en las páginas de contenido individual

![screen shot 2016-01-27 at 14 52 58](https://cloud.githubusercontent.com/assets/7160350/12615434/f769f92a-c505-11e5-8525-9c249cdd0875.png)

**Comment by aitormendez** [comment]
Ok, cuando lo subas, lo miro.

**Comment by muihlinn** [comment]
Ejemplo: http://iac.imaginarymagnitude.net/noticias/convocatorias/bug-aitor.html

**Comment by aitormendez** [comment]
Arreglado. Tienes que cambiar ligeramente la estructura, metiendo el contenido del LI activo en un SPAN
https://github.com/aitormendez/iac-web/blob/master/_noticia.html#L20-L22
y compilar less
